### ISSUE TITLE
Error: Read failed. Insufficient number of disks online - but 4 of 4 disks are online

### ISSUE THREAD

**Issue by mfld-pub** [minio/minio#10505]
Single node setup..
Since updating a few weeks ago I notice high I/O load on the server. I thought maybe a SMART extended is running or minio is healing and it will settle. But days passed and it's still going crazy. I 

**## Expected Behavior**
Minio should heal as normal and use "normal" system resources given there are plenty of resources and 4 disks.

## Current Behavior
Running minio like this: 
`minio server --address :443 --certs-dir /minio/.minio/certs/ /minio/disk1 /minio/disk2 /minio/disk3 /minio/disk4`

Where /minio/disk1-4 are dedicated ext4 partitions on physical drives 1-4.

The log shows 3 areas of concern:

1) It claims each of the disks has some corrupted files, example here refers to disk3 but the other disks also show up in the log 

> Error: Disk: /minio/disk3 returned file is corrupted

2) It claims not all disks are online 

> Error: Read failed. Insufficient number of disks online

But I believe they are: 

>    Version: 2020-09-17T04:49:20Z
>    Network: 1/1 OK
>    Drives: 4/4 OK
> 
> 2.5 TiB Used, 11 Buckets, 24,270 Objects
> 4 drives online, 0 drives offline

3) It claims storage resources are insufficient

> Error: Storage resources are insufficient for the read operation.

But I see plenty of RAM, space on the minio partitions and free inodes

## Steps to Reproduce (for bugs)

1. `minio server --address :443 --certs-dir /minio/.minio/certs/ /minio/disk1 /minio/disk2 /minio/disk3 /minio/disk4`
2. Wait a few minutes then `df -i` to verify there is space and inodes
3. Inspect system load in htop / glances. Load is normally < 1.0. Now it is > 4.0
4. Inspect minio console log. Bitrot detection will start throwing errors.
5. Run `mc admin info local ` to confirm all disk show online

## Context
* System has been in production for several years. I wonder if some schema has changed since it was originally provisioned and one of my minio updates went wrong somehow.

* All 4 disks passed SMART short tests today.

* minio OBD completed successfully and shows all green.

![obd](https://user-images.githubusercontent.com/66289900/93452254-c8ad2100-f90a-11ea-8c4c-13f0b50feef2.JPG)

## Your Environment

`minio version RELEASE.2020-09-17T04-49-20Z`

`mc version RELEASE.2020-09-03T00-08-28Z`

```
df -h
Filesystem            Size  Used Avail Use% Mounted on
udev                   16G     0   16G   0% /dev
tmpfs                 3.2G  1.2M  3.2G   1% /run
/dev/mapper/vg0-root   59G   37G   19G  67% /
tmpfs                  16G     0   16G   0% /dev/shm
tmpfs                 5.0M     0  5.0M   0% /run/lock
tmpfs                  16G     0   16G   0% /sys/fs/cgroup
/dev/sdc4             9.0T  1.6T  7.0T  19% /minio/disk3
/dev/sdb4             9.0T  1.6T  7.0T  18% /minio/disk2
/dev/sda4             9.0T  1.6T  7.0T  19% /minio/disk1
/dev/sdd4             9.0T  1.6T  7.0T  18% /minio/disk4
/dev/mapper/vg0-tmp    32G   49M   30G   1% /tmp
/dev/md0              2.0G  216M  1.7G  12% /boot
tmpfs                 3.2G     0  3.2G   0% /run/user/0
```

```
df -i
Filesystem              Inodes  IUsed     IFree IUse% Mounted on
udev                   4075107    578   4074529    1% /dev
tmpfs                  4083006    935   4082071    1% /run
/dev/mapper/vg0-root   3932160 158869   3773291    5% /
tmpfs                  4083006      1   4083005    1% /dev/shm
tmpfs                  4083006      3   4083003    1% /run/lock
tmpfs                  4083006     18   4082988    1% /sys/fs/cgroup
/dev/sdc4            303038464 546697 302491767    1% /minio/disk3
/dev/sdb4            303038464 478115 302560349    1% /minio/disk2
/dev/sda4            303038464 528954 302509510    1% /minio/disk1
/dev/sdd4            303038464 472993 302565471    1% /minio/disk4
/dev/mapper/vg0-tmp    2097152     24   2097128    1% /tmp
/dev/md0                131072    313    130759    1% /boot
tmpfs                  4083006     11   4082995    1% /run/user/0
```

```
free -mt
              total        used        free      shared  buff/cache   available
Mem:          31898         439       24114           1        7344       31056
Swap:         32767           0       32767
Total:        64666         439       56882
```

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
```

```
uname -r
4.15.0-117-generic
```
Some fragments from the OBD json that may be relevant:

```
        "crawler": {
          "_": [
            {
              "key": "bitrotscan",
              "value": "off"
            }

        "compression": {
          "_": [
            {
              "key": "enable",
              "value": "off"
            },

        "backend": {
          "backendType": "Erasure",
          "onlineDisks": 4,
          "rrSCData": 2,
          "rrSCParity": 2,
          "standardSCData": 2,
          "standardSCParity": 2
        },
```

I can sanitize the whole thing and attach it if it helps.

Edit: This might be useful:

```
/mc admin config export local
region name=
storage_class standard= rrs=EC:2
# cache drives= exclude= expiry=90 quota=80 after=0 watermark_low=70 watermark_high=80 range=on
# compression enable=off extensions=.txt,.log,.csv,.json,.tar,.xml,.bin mime_types=text/*,application/json,application/xml
# etcd endpoints= path_prefix= coredns_path=/skydns client_cert= client_cert_key=
# identity_openid config_url= client_id= claim_name=policy claim_prefix= jwks_url= scopes=
# identity_ldap server_addr= sts_expiry=1h username_format= group_search_filter= group_name_attribute= group_search_base_dn= tls_skip_verify=off username_search_filter= username_search_base_dn= server_insecure=off server_starttls=off
# policy_opa url= auth_token=
# kms_vault endpoint= key_name= auth_type=approle auth_approle_id= auth_approle_secret= capath= key_version= namespace=
# kms_kes endpoint= key_name= cert_file= key_file= capath=
api requests_max=0 requests_deadline=10s ready_deadline=10s cors_allow_origin=* remote_transport_deadline=2h
crawler bitrotscan=off
# logger_webhook enable=off endpoint= auth_token=
# audit_webhook enable=off endpoint= auth_token=
# notify_webhook enable=off endpoint= auth_token= queue_limit=0 queue_dir= client_cert= client_key=
# notify_amqp enable=off url= exchange= exchange_type= routing_key= mandatory=off durable=off no_wait=off internal=off auto_deleted=off delivery_mode=0 queue_limit=0 queue_dir=
# notify_kafka enable=off topic= brokers= sasl_username= sasl_password= client_tls_cert= client_tls_key= tls_client_auth=0 sasl=off tls=off tls_skip_verify=off queue_limit=0 queue_dir= sasl_mechanism=plain version=
# notify_mqtt enable=off broker= topic= password= username= qos=0 keep_alive_interval=0s reconnect_interval=0s queue_dir= queue_limit=0
# notify_nats enable=off address= subject= username= password= token= tls=off tls_skip_verify=off cert_authority= client_cert= client_key= ping_interval=0 streaming=off streaming_async=off streaming_max_pub_acks_in_flight=0 streaming_cluster_id= queue_dir= queue_limit=0
# notify_nsq enable=off nsqd_address= topic= tls=off tls_skip_verify=off queue_dir= queue_limit=0
# notify_mysql enable=off format=namespace host= port= username= password= database= dsn_string= table= queue_dir= queue_limit=0
# notify_postgres enable=off format=namespace connection_string= table= host= port= username= password= database= queue_dir= queue_limit=0
# notify_elasticsearch enable=off url= format=namespace index= queue_dir= queue_limit=0 username= password=
# notify_redis enable=off format=namespace address= key= password= queue_dir= queue_limit=0
```

In case it matters: The partitions are LUKS encrypted but unlocked during preboot so minio can access them as soon as started. Running super stable for years until now.

**Comment by harshavardhana** [comment]
> 1. It claims each of the disks has some corrupted files, example here refers to disk3 but the other disks also show up in the log
> 
> > Error: Disk: /minio/disk3 returned file is corrupted
> 
> 1. It claims not all disks are online
> 
> > Error: Read failed. Insufficient number of disks online

It is saying this because it found objects to be in a corrupted state, - share the entire logs here @mfld-pub not just a snippet from the entries.

**Comment by mfld-pub** [comment]
> > 1. It claims each of the disks has some corrupted files, example here refers to disk3 but the other disks also show up in the log
> > 
> > > Error: Disk: /minio/disk3 returned file is corrupted
> > 
> > 
> > 
> > 1. It claims not all disks are online
> > 
> > > Error: Read failed. Insufficient number of disks online
> 
> It is saying this because it found objects to be in a corrupted state, - share the entire logs here @mfld-pub not just a snippet from the entries.

Gladly! 

I just did `./mc admin heal -r local` and it completes seemingly OK.

I have attached here sanitized session log and OBD output.
[sessionlog.txt](https://github.com/minio/minio/files/5238187/sessionlog.txt)
[local-obd_20200917091546.json.txt](https://github.com/minio/minio/files/5238188/local-obd_20200917091546.json.txt)

**Comment by harshavardhana** [comment]
As you can see you have lost quorum @mfld-pub 

```
 API: SYSTEM()
 Time: 07:52:11 UTC 09/17/2020
 DeploymentID: 4bafac5f-5f02-447c-b2dc-feeb8b6b1072
 Error: Disk: /minio/disk4 returned file is corrupted
        2: cmd/bitrot-whole.go:74:cmd.(*wholeBitrotReader).ReadAt()
        1: cmd/erasure-decode.go:163:cmd.(*parallelReader).Read.func1()

 API: SYSTEM()
 Time: 07:52:11 UTC 09/17/2020
 DeploymentID: 4bafac5f-5f02-447c-b2dc-feeb8b6b1072
 Error: Disk: /minio/disk4 returned file is corrupted
        2: cmd/bitrot-whole.go:74:cmd.(*wholeBitrotReader).ReadAt()
        1: cmd/erasure-decode.go:163:cmd.(*parallelReader).Read.func1()

 API: SYSTEM()
 Time: 07:52:11 UTC 09/17/2020
 DeploymentID: 4bafac5f-5f02-447c-b2dc-feeb8b6b1072
 Error: Disk: /minio/disk2 returned file is corrupted
        2: cmd/bitrot-whole.go:74:cmd.(*wholeBitrotReader).ReadAt()
        1: cmd/erasure-decode.go:163:cmd.(*parallelReader).Read.func1()

 API: SYSTEM()
 Time: 07:52:11 UTC 09/17/2020
 DeploymentID: 4bafac5f-5f02-447c-b2dc-feeb8b6b1072
 Error: Disk: /minio/disk2 returned file is corrupted
        2: cmd/bitrot-whole.go:74:cmd.(*wholeBitrotReader).ReadAt()
        1: cmd/erasure-decode.go:163:cmd.(*parallelReader).Read.func1()

 API: SYSTEM()
 Time: 07:52:11 UTC 09/17/2020
 DeploymentID: 4bafac5f-5f02-447c-b2dc-feeb8b6b1072
 Error: Disk: /minio/disk1 returned file is corrupted
        2: cmd/bitrot-whole.go:74:cmd.(*wholeBitrotReader).ReadAt()
        1: cmd/erasure-decode.go:163:cmd.(*parallelReader).Read.func1()

 API: SYSTEM()
 Time: 07:52:11 UTC 09/17/2020
 DeploymentID: 4bafac5f-5f02-447c-b2dc-feeb8b6b1072
 Error: Disk: /minio/disk1 returned file is corrupted
        2: cmd/bitrot-whole.go:74:cmd.(*wholeBitrotReader).ReadAt()
        1: cmd/erasure-decode.go:163:cmd.(*parallelReader).Read.func1()
```

Your files have corruption i.e there has been bit-rot on them healing is triggering these messages 
while it is trying to heal them.  Looks like your have bad sectors are going to die soon.

**Comment by harshavardhana** [comment]
Of course, this is new because we have auto-heal now, which is able to report these issues. It is not across all objects but some of them @mfld-pub so you need to figure out which file is this.

**Comment by mfld-pub** [comment]
Alright. I will prepare to migrate off or do a backup and have the disks replaced once I identify which one it is. Takes a while with those 10TB rust devices.
When it says 

> Error: Disk: /minio/disk1 returned file is corrupted

Is there a way to debug and have it tell me the affected object IDs ? There are "only" 25k object here but it always returns good on `mc admin heal`. Other than by trial and error, how to identify the effected objects ?

**Comment by harshavardhana** [comment]
> Is there a way to debug and have it tell me the affected object IDs ? There are "only" 25k object here but it always returns good on `mc admin heal`. Other than by trial and error, how to identify the effected objects ?

I can add some logs here, looks like it would worth adding object names here while it is printed.

**Comment by mfld-pub** [comment]
> I can add some logs here, looks like it would worth adding object names here while it is printed.

That would be awesome!

I might use this event as an opportunity to migrate to a newer server altogether. Or go with these Gen Z / millenial containerized setups. I will try identify which physical drive(s) are failing and take it from there.

**Comment by harshavardhana** [comment]
Please grab it from here @mfld-pub 
```
mc cp -a play/testbucket/minio-issue#10505 ./minio
```

**Comment by mfld-pub** [comment]
We ran SMART extended and offlines on all 4 drives. Strangely they come back perfect.
I expected to have a hardware fault of sorts. 
The logging output was useful in identifying oid. I have inspected them and they are not corrupted. How to proceed ?

**Comment by harshavardhana** [comment]
> We ran SMART extended and offlines on all 4 drives. Strangely they come back perfect.
> I expected to have a hardware fault of sorts.
> The logging output was useful in identifying oid. I have inspected them and they are not corrupted. How to proceed ?

They were corrupted upon read, I am not sure if the filesystem was wonky at the time. If the messages are not printed anymore then disk FS has somehow corrected itself. Since you have layered system here I wouldn't rule out luks doing something wonky.

**Comment by harshavardhana** [comment]
> > We ran SMART extended and offlines on all 4 drives. Strangely they come back perfect.
> > I expected to have a hardware fault of sorts.
> > The logging output was useful in identifying oid. I have inspected them and they are not corrupted. How to proceed ?
> 
> They were corrupted upon read, I am not sure if the filesystem was wonky at the time. If the messages are not printed anymore then disk FS has somehow corrected itself. Since you have layered system here I wouldn't rule out luks doing something wonky.

Note filesystem level corruptions, minor bit flips are never captured by SMART tools since they don't know the actual block map of a filesystem.

**Comment by mfld-pub** [comment]
I still have faith in the hardware and the state of the ext4 partitions. 

The data minio is serving there is from Nextcloud. 

Having inspected the OIDs and compared them against the data served by Nextcloud I can see no diffs. 

From sampling I can see that nothing is corrupted but minio will keep flagging them each time it scans. I propose removing them and rewriting them from NextCloud. If I download  an OID it is complaining about and do a sha256sum of it I can then find the corresponding file with the same hash in the user's Nextcloud drive. There is no actual corruption. 

Example: The log says OID 17968 is bad:

 ```
Error: Disk: /minio/disk1 -> storphiupw/urn:oid:17968/part.1 returned file is corrupted
 Error: Disk: /minio/disk1 -> storphiupw/urn:oid:17968/part.1 returned file is corrupted
  Error: Disk: /minio/disk3 -> storphiupw/urn:oid:17968/part.1 returned file is corrupted
 Error: Disk: /minio/disk3 -> storphiupw/urn:oid:17968/part.1 returned file is corrupted
  Error: Disk: /minio/disk2 -> storphiupw/urn:oid:17968/part.1 returned file is corrupted
  Error: Disk: /minio/disk2 -> storphiupw/urn:oid:17968/part.1 returned file is corrupted
   Error: Disk: /minio/disk4 -> storphiupw/urn:oid:17968/part.1 returned file is corrupted
 API: SYSTEM(bucket=h3h26-testbucket, object=urn:oid:17968)

```
I retrieve the object and hash it:

f81371042a36c172bca52957dd653a79f31fa6b08b214b6d6b561b1050762191  urn_oid_17968

I find that the user / application has a PDF with that hash:

f81371042a36c172bca52957dd653a79f31fa6b08b214b6d6b561b1050762191  Entitlement_Details_2016.pdf

I inspect the PDF and it appears intact.

Our setup is from 2017. I notice

 ```
"crawler": {
          "_": [
            {
              "key": "bitrotscan",
              "value": "off"
            }

Should this be ON ?
```

**Comment by harshavardhana** [comment]
> Having inspected the OIDs and compared them against the data served by Nextcloud I can see no diffs.

You have quorum @mfld-pub which is allowing you to read the content still, but indeed they are corrupted on some drives not all of them.  Were you able to read these objects using tools like `mc cp` ?

> "crawler": {
>          "_": [
>            {
>              "key": "bitrotscan",
>              "value": "off"
>            }

Enabling this should fix them but we also trigger bitrot heal upon reads its not necessary to set this value.

**Comment by mfld-pub** [comment]
> If the messages are not printed anymore then disk FS has somehow corrected itself.

The messages are printed still. Shortly after the service is started. Minio declares corruption.

> You have quorum @mfld-pub which is allowing you to read the content still, but indeed they are corrupted on some drives not all of them.

That is the part I do not understand. I thought that is what heal should be for. To fix these things as long as there is quorum.

> Were you able to read these objects using tools like mc cp ?

Yes Sir, that is how I did it. I retrieved the OID from the log output with mc or Cloudberry S3 explorer. I did a sha256sum of the retrieved file and then found that file intact on the user's Nextcloud folder and local machine. Hash matches in all cases.

**Comment by harshavardhana** [comment]
> > If the messages are not printed anymore then disk FS has somehow corrected itself.
> 
> The messages are printed still. Shortly after the service is started. Minio declares corruption.
> 
> > You have quorum @mfld-pub which is allowing you to read the content still, but indeed they are corrupted on some drives not all of them.
> 
> That is the part I do not understand. I thought that is what heal should be for. To fix these things as long as there is quorum.
> 
> > Were you able to read these objects using tools like mc cp ?
> 
> Yes Sir, that is how I did it. I retrieved the OID from the log output with mc or Cloudberry S3 explorer. I did a sha256sum of the retrieved file and then found that file intact on the user's Nextcloud folder and local machine. Hash matches in all cases.

NOTE: you may also copy the readable object as a server side copy

`mc cp alias/bucket/oid alias/bucket/oid.new` 
`mc rm alias/bucket/oid`
`mc cp alias/bucket/oid.new alias/bucket/oid`
`mc rm alias/bucket/oid.new`

A get on the object should trigger the heal, not sure why it's not happening. I will verify.

**Comment by mfld-pub** [comment]
I did try 

`mc admin heal -r local`

earlier on thinking this will force everything to be scanned and healed but it completes without errors, 100% green on all buckets. Then the issue persists.

In any case I think that method is deprecated. I need to re-learn minio. Much has changed from 2016 :)

**Comment by harshavardhana** [comment]
> I did try
> 
> `mc admin heal -r local`
> 
> earlier on thinking this will force everything to be scanned and healed but it completes without errors, 100% green on all buckets. Then the issue persists.
> 
> In any case I think that method is deprecated. I need to re-learn minio. Much has changed from 2016 :)

`mc admin heal` doesn't do bit-rot check by default. We have auto-heal now so that would automatically do it if you enable bitrot-scan. I just wonder why its not able to fix it.

**Comment by mfld-pub** [comment]
I will try to enable bitrot scan with `mc admin config set local crawler bitrotscan=on` and report back

**Comment by mfld-pub** [comment]
> I will try to enable bitrot scan with mc admin config set local crawler bitrotscan=on and report back

This ran for the past 2 days with no discernible difference.

**Comment by harshavardhana** [comment]
does it still complain about the old object? @mfld-pub 

```
mc cp alias/bucket/oid alias/bucket/oid.new
mc rm alias/bucket/oid
mc cp alias/bucket/oid.new alias/bucket/oid
mc rm alias/bucket/oid.new
```

you can try server side copy to re-do the object into newer format.

**Comment by mfld-pub** [comment]
I will try that. But it seems there are hundreds of effected OID and in some cases they have part.1 appended.

Example: urn:oid:7613/part.1
