### ISSUE TITLE
minio server heals data into root disk mountpoint dir when the external drive go down

### ISSUE THREAD

**Issue by mkpavilion** [minio/minio#11810]
I am using minio distributed object store with below setup info.
minio version RELEASE.2021-01-16T02-19-44Z
EC set 1 of size 16 with parity N-2; Minio nodes are 4 and total 16 NVMe SSDs;
So each node is hosting 4 Minio logical drives (mountpoints). Node is in docker container form running minio instance.

In this scenario, after putting some buckets/objects into the object store, if 1 or 2 drives are taken down then seems minio automatically fires *healing* for these powered down drives causing the object data restore into the root disk of the nodes who owns these powered down drives.

## Expected Behavior

This is a json snippet from the mc admin info output which tells the minio node has identified the logical drive (d31 external drive powered off) is indeed "rootDisk" but still it considers the drive state "ok" and executes "healing" doing objects data restore. This shall not happen as originally /mnt/pds3/d31 path is a mountpoint to an external drive (id: d31) than a local fs folder.
{
	"endpoint": "http://192.168.40.39:4420/mnt/pds3/d31",
	"rootDisk": true,
	"path": "/mnt/pds3/d31",
	"healing": true,
	"state": "ok",
	"uuid": "7e73153a-f2c5-407e-a2e8-0486efe6c427",
	"totalspace": 4712517632,
	"usedspace": 3032072192,
	"availspace": 1680445440
      }

## Current Behavior

As explained above, object data recovery happens under local fs directory.

## Possible Solution

When minio distributed setup is initialized first time, it should do bookkeeping of the logical drives path *nature* ie. whether the path is local fs path or a mountpoint to an external drive /block device. Accordingly it shall consider the path status "ok" or "not ok" for healing.

## Steps to Reproduce (for bugs)

With above d-minio setup, below steps can be tried out to repro the issue.
1. Say, on node1, drives d1/d2/d3/d4 are mounted as /mnt/d1, /mnt/d2, /mnt/d3 and /mnt/d4. And on node2, drives d5/d6/d7/d8 are mounted in respective mountpoints.
2. Now power down drives 1 and 5
3. mountpoints /mnt/d1 @node1 and /mnt/d5 @node2 are dis-appeared
4. Immediately "mc admin info" executed against any one of the 4 nodes, tells that /mnt/d1 and /mnt/d5 logical drives are "offline"
5. The drives are kept powered off only but after 1 min or so, minio cluster triggers auto-heal causing the present objects data recovery inside /mnt/d1 and /mnt/d5 local folders @ the nodes node1 and node2 respectively.

## Context

As I do not have sufficient storage at my local os disk, healing object store drive makes it full causing docker and other processes stop functioning.

## Regression
 Not sure

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2021-01-16T02-19-44Z
* Server setup and configuration: Linux host running docker container based minio nodes. Docker version 19.03.13, build 4484c46d9d
* Operating System and version (`uname -a`): Linux node13 5.4.19 #1 SMP -svn9755 Mon Mar 15 15:01:43 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
This is fixed in recent releases @mkpavillion

**Comment by mkpavilion** [comment]
@harshavardhana, thanks for your reply
We found that with 17 Mar minio server build it wasn't functional so tested rebuild functionality with the latest one RELEASE.2021-03-26T00-00-41Z.

Our observation is the issue gets still reproduced *sometimes* but not always like before.

Setup: Minio 3 endpoints (pds3-node13/pds3-node14/pds3-node15) over docker containers having total 16 drives forming 1 EC (EC 14+2).

== SUCCESS CASE ================================
drive d20 owned by pds3-node13 powered off
minio correctly identifies mount point is root disk when external drive goes down. This is the desired functionality.
================================================

Mar 30 06:35:59 pds3-node13 root[63]: Found drives to heal 1, proceeding to heal content...
Mar 30 06:36:05 pds3-node13 root[63]: Found unformatted drive http://192.168.201.38:4420/mnt/pds3/d20, attempting to heal...
Mar 30 06:36:09 pds3-node13 root[63]: Disk `/mnt/pds3/d20` the same as the system root disk.
Mar 30 06:36:09 pds3-node13 root[63]: Disk will not be used. Please supply a separate disk and restart the server.
Mar 30 06:36:09 pds3-node13 root[63]: Found drives to heal 1, proceeding to heal content...
Mar 30 06:36:19 pds3-node13 root[63]: Disk `/mnt/pds3/d20` the same as the system root disk.
Mar 30 06:36:19 pds3-node13 root[63]: Disk will not be used. Please supply a separate disk and restart the server.

== ISSUE-1 ====================================
minio @ pds3-node13 exited abruptly on second drive powered off owned by some other node (pds3-node14). Here is the log snippet before it exited.
================================================
Mar 30 06:42:04 pds3-node13 root[54]: 
Mar 30 06:42:04 pds3-node13 root[54]: API: ServerInfo()
Mar 30 06:42:04 pds3-node13 root[54]: Time: 06:42:04 UTC 03/30/2021
Mar 30 06:42:04 pds3-node13 root[54]: DeploymentID: 6648814c-7700-4101-8a63-19b8aa1a8769
Mar 30 06:42:04 pds3-node13 root[54]: RequestID: 16710B9A71F4BA79
Mar 30 06:42:04 pds3-node13 root[54]: RemoteHost: 10.10.10.100
Mar 30 06:42:04 pds3-node13 root[54]: Host: 192.168.11.240:4420
Mar 30 06:42:04 pds3-node13 root[54]: UserAgent: MinIO (linux; amd64) madmin-go/0.0.1 mc/DEVELOPMENT.2021-03-26T10-24-22Z
Mar 30 06:42:04 pds3-node13 root[54]: Error: Drive http://192.168.11.241:4420/mnt/pds3/d21 returned an error (disk is faulty) (*fmt.wrapError)
Mar 30 06:42:04 pds3-node13 root[54]:        4: cmd/logger/logonce.go:53:logger.(*logOnceType).logOnceIf()
Mar 30 06:42:04 pds3-node13 root[54]:        3: cmd/logger/logonce.go:93:logger.LogOnceIf()
Mar 30 06:42:04 pds3-node13 root[54]:        2: cmd/erasure-metadata-utils.go:138:cmd.readAllFileInfo.func1()
Mar 30 06:42:04 pds3-node13 root[54]:        1: pkg/sync/errgroup/errgroup.go:122:errgroup.(*Group).Go.func1()
Mar 30 06:42:04 pds3-node13 root[54]: Disk `/mnt/pds3/d20` the same as the system root disk.
Mar 30 06:42:04 pds3-node13 root[54]: Disk will not be used. Please supply a separate disk and restart the server.
Mar 30 06:42:04 pds3-node13 root[54]: Found drives to heal 1, proceeding to heal content...

== ISSUE-2 ====================================
- pds3-node13 minio process crashing continuously after its drive 20 came back; remounted and the drive rebuild started. During this time drive 21 belonging to pds3-node14 was still powered off.
- Also found that / partition at pds-node14 container was filled up due to its minio node done rebuild to root disk parition.
===============================================

Mar 30 06:59:52 pds3-node13 root[60]: UserAgent: MinIO (linux; amd64) minio-go/v7.0.8 mc/RELEASE.2021-01-30T00-50-42Z
Mar 30 06:59:52 pds3-node13 root[60]: Error: remote listing canceled: timeout: list bbfdb8e5-7eac-4b9b-b048-14970ffe3bfa not updated (*fmt.wrapError)
Mar 30 06:59:52 pds3-node13 root[60]:        5: cmd/metacache-server-pool.go:228:cmd.(*erasureServerPools).listPath()
Mar 30 06:59:52 pds3-node13 root[60]:        4: cmd/erasure-server-pool.go:966:cmd.(*erasureServerPools).ListObjects()
Mar 30 06:59:52 pds3-node13 root[60]:        3: cmd/erasure-server-pool.go:882:cmd.(*erasureServerPools).ListObjectsV2()
Mar 30 06:59:52 pds3-node13 root[60]:        2: cmd/bucket-listobjects-handlers.go:243:cmd.objectAPIHandlers.ListObjectsV2Handler()
Mar 30 06:59:52 pds3-node13 root[60]:        1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()
Mar 30 06:59:52 pds3-node13 root[60]: 
Mar 30 06:59:52 pds3-node13 root[60]: API: ListObjectsV2(bucket=bucket1)
Mar 30 06:59:52 pds3-node13 root[60]: Time: 06:59:52 UTC 03/30/2021
Mar 30 06:59:52 pds3-node13 root[60]: DeploymentID: 6648814c-7700-4101-8a63-19b8aa1a8769
Mar 30 06:59:52 pds3-node13 root[60]: RequestID: 16710C97BE327831
Mar 30 06:59:52 pds3-node13 root[60]: RemoteHost: 192.168.11.81
Mar 30 06:59:52 pds3-node13 root[60]: Host: 192.168.11.240:4420
Mar 30 06:59:52 pds3-node13 root[60]: UserAgent: MinIO (linux; amd64) minio-go/v7.0.8 mc/RELEASE.2021-01-30T00-50-42Z
Mar 30 06:59:52 pds3-node13 root[60]: Error: remote listing canceled: timeout: list bbfdb8e5-7eac-4b9b-b048-14970ffe3bfa not updated (*fmt.wrapError)
Mar 30 06:59:52 pds3-node13 root[60]:        4: cmd/erasure-server-pool.go:976:cmd.(*erasureServerPools).ListObjects()
Mar 30 06:59:52 pds3-node13 root[60]:        3: cmd/erasure-server-pool.go:882:cmd.(*erasureServerPools).ListObjectsV2()
Mar 30 06:59:52 pds3-node13 root[60]:        2: cmd/bucket-listobjects-handlers.go:243:cmd.objectAPIHandlers.ListObjectsV2Handler()
Mar 30 06:59:52 pds3-node13 root[60]:        1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()
Mar 30 06:59:52 pds3-node13 root[60]: 
Mar 30 06:59:52 pds3-node13 root[60]: API: ListObjectsV2(bucket=bucket1)
Mar 30 06:59:52 pds3-node13 root[60]: Time: 06:59:52 UTC 03/30/2021
Mar 30 06:59:52 pds3-node13 root[60]: DeploymentID: 6648814c-7700-4101-8a63-19b8aa1a8769
Mar 30 06:59:52 pds3-node13 root[60]: RequestID: 16710C97BE327831
Mar 30 06:59:52 pds3-node13 root[60]: RemoteHost: 192.168.11.81
Mar 30 06:59:52 pds3-node13 root[60]: Host: 192.168.11.240:4420
Mar 30 06:59:52 pds3-node13 root[60]: UserAgent: MinIO (linux; amd64) minio-go/v7.0.8 mc/RELEASE.2021-01-30T00-50-42Z
Mar 30 06:59:52 pds3-node13 root[60]: Error: remote listing canceled: timeout: list bbfdb8e5-7eac-4b9b-b048-14970ffe3bfa not updated (*fmt.wrapError)
Mar 30 06:59:52 pds3-node13 root[60]:        4: cmd/api-errors.go:2009:cmd.toAPIErrorCode()
Mar 30 06:59:52 pds3-node13 root[60]:        3: cmd/api-errors.go:2034:cmd.toAPIError()
Mar 30 06:59:52 pds3-node13 root[60]:        2: cmd/bucket-listobjects-handlers.go:245:cmd.objectAPIHandlers.ListObjectsV2Handler()
Mar 30 06:59:52 pds3-node13 root[60]:        1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()

== ISSUE-3 =======================================
- Even when we powered down 2 drives we observed rebuild started healing data into local root disk directories.
===============================================

Please can you comment.

**Comment by klauspost** [comment]
There is nothing related to a crash in these logs. These are just timeouts from listings running on a server that died. Post the logs from the crash of the server running or look for the work "panic" or similar error message.

If there is indeed nothing in the logs check if the process was killed by the operating system.

**Comment by mkpavilion** [comment]
There is no "panic" or like error message, but minio process was not listed in "ps -aef" output.
After this line, minio @ pds3-node13 just exited.
>> Mar 30 06:42:04 pds3-node13 root[54]: Found drives to heal 1, proceeding to heal content...

This process was running in a docker container which was pretty healthy and no other external process/watcher killed it either.

As well while doing rebuild of one drive@pds3-node13 node, the object store rebuild has recovered files of other powered off drive @pds3-node14 into its local / file system. And after that certainly pds3-node13 minio proc started crashing continuously, even started again and again.

**Comment by harshavardhana** [comment]
Oh so you are using docker @mkpavilion - how about using baremetal?  

We have one pending issue in docker that needs to be addressed, are you using /var pointing to a different partition than / ?

**Comment by mkpavilion** [comment]
@harshavardhana,
Hi, Thanks for the info. Yes we are using docker containers to run each minio node. Sorry I could not verify this same with baremetal so far. If I get time I will certainly confirm the behavior with baremetal.
No /var and / are over the same partition.
Here is df -h o/p for your reference taken within a container. This /mnt/pds3/dXY are external nvme drives mountpoints which host has bind mounted to the container.

bash-4.4# df -h
Filesystem       Size  Used Avail Use% Mounted on
overlay          4.7G  2.8G  1.6G  64% /
tmpfs             64M     0   64M   0% /dev
tmpfs             32G     0   32G   0% /sys/fs/cgroup
shm               64M     0   64M   0% /dev/shm
/dev/sda1        4.7G  2.8G  1.6G  64% /mnt/pds3
tmpfs             32G  2.6M   32G   1% /run
/dev/rnvmed28n1   12T  172G   12T   2% /mnt/pds3/d28
/dev/rnvmed33n1   12T  172G   12T   2% /mnt/pds3/d33
/dev/rnvmed25n1   12T  172G   12T   2% /mnt/pds3/d25

A couple of observations,

1. If I forcefully restrict /mnt/pds3/dXY as Read-Only when its external drive goes down then minio is not able to rebuild into it due to lack of access permission and also identifies it is a root disk. And before that I am removing .minio.sys folder from it as well, which helps minio to confirm that the drive is "unformatted" and it marks "healing" true for it. (this status is shown in admin info o/p for that drive). When that external physical drive is back, removal of RO permission and mounting external drive over the same mountpoint directory, minio rebuild handles it well as desired.
I am wondering if minio node shall check if the base directory it is creating .minio.sys meta dir is a root disk or not.

2. When I power down second drive with that EC, then any ONE random node minio process within that EC abruptly exits. Not sure why. No crash found as such. But this case is 100% reproducible that we saw. And if the minio process over this node started again then it remains stable. EC-16 with 14 drives online keeps functioning in degraded mode. But ONE time some minio process within that EC-set fails/exists.

Thanks.
Mandar

**Comment by mkpavilion** [comment]
> Oh so you are using docker @mkpavilion - how about using baremetal?
> 
> We have one pending issue in docker that needs to be addressed, are you using /var pointing to a different partition than / ?

@harshavardhana,
Is it possible for you to comment when this issue will be addressed?
Accordingly I can plan picking up that upcoming release.

Thanks.
Mandar
