### ISSUE TITLE
LDAP - invalid login - Regression introduced some point between RELEASE.2022-07-08T00-05-23Z and RELEASE.2022-08-11T04-37-28Z

### ISSUE THREAD

**Issue by abjoseph** [minio/minio#15527]
## Expected Behavior

Navigate to "embedded" console at configured port (9001 in this case) and enter LDAP/AD username and password to login to portal UI.

## Current Behavior

I'm getting a "invalid login / http 401" error response when using LDAP/AD credentials. I have to resort to root user and password to login.

## Possible Solution

Revert docker image tag from current version with issue ***RELEASE.2022-08-11T04-37-28Z*** to last known working release ***RELEASE.2022-07-08T00-05-23Z***

## Steps to Reproduce (for bugs)

1. Spin up a docker instance of minio with the image/tag version ***RELEASE.2022-07-08T00-05-23Z*** and configure ldap integration.
2. configure target LDAP/AD user with console admin access using `mc admin policy set minio consoleAdmin user="CN=John Doe,CN=Users,DC=Domain,DC=com"`
3. Confirm access using LDAP/AD target user configured above.
4. Update minio instance to latest version as of this bug report ***RELEASE.2022-08-11T04-37-28Z***
5. Test logging in to the console using the same target LDAP/AD user as confirmed above.

## Context

I'm not able to login to console to perform administrative actions

## Regression

Yes
Introduced in a release after **RELEASE.2022-07-08T00-05-23Z**, I haven't tested every single version to identify the *first* offending release.

### Version used: 

`minio version RELEASE.2022-07-08T00-05-23Z`

### Operating System and version: 

`Linux lhdock01p 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### Server setup and configuration: 

```
version: "3"
services:
  minio-external:
    image: minio/minio:RELEASE.2022-07-08T00-05-23Z
    container_name: minio-external
    command: server /data /data1 /data2 /data3 --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
    environment:
      MINIO_BROWSER_REDIRECT_URL: "https://minio.example.com"
      MINIO_DOMAIN: "blob.example.com"
      MINIO_ROOT_PASSWORD: "<root-password>"
      MINIO_ROOT_USER: "<root-user-id>"
      MINIO_SERVER_URL: "https://blob.example.com"
      MINIO_IDENTITY_LDAP_SERVER_ADDR: "Example.org:389"
      MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN: "CN=minio-ad,DC=Example,DC=com"
      MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN: "CN=Users,DC=Example,DC=com"
      MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER: "(&(sAMAccountName=%s)(memberOf=CN=Minio Users,CN=Minio,OU=Application Groups,DC=Example,DC=com))"
      MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD: "<random-password>"
      MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER: "(&(objectClass=group)(member=%d))"
      MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN: "CN=Minio,OU=Application Groups,DC=Example,DC=com"
      MINIO_IDENTITY_LDAP_SERVER_STARTTLS: "true"
      MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY: "true"
    volumes:
      - "minio_1:/data"
      - "minio_2:/data1"
      - "minio_3:/data2"
      - "minio_4:/data3"
```

**Comment by harshavardhana** [comment]
@abjoseph can you provide `mc admin trace -a --funcname sts* --funcname admin* --funcname s3*`  output?  - keep it running and attempt a login.

**Comment by harshavardhana** [comment]
Also please share server-side logs

**Comment by harshavardhana** [comment]
> Yes
> Introduced in a release after **RELEASE.2022-07-08T00-05-23Z**, I haven't tested every single version to identify the _first_ offending release.

Please test `RELEASE.2022-08-08T18-34-09Z`  and let us know.

**Comment by codemicro** [comment]
It's also worth noting that this bug also appeared to have stopped OIDC from being displayed as a SSO option on the login screen at all, in favour of the standard username/password form. This was despite OIDC being properly configured.

This behaviour was introducted by a recent release and fixed with the most latest release, presumably because of the linked PR.

**Comment by harshavardhana** [comment]
> It's also worth noting that this bug also appeared to have stopped OIDC from being displayed as a SSO option on the login screen at all, in favour of the standard username/password form. This was despite OIDC being properly configured.
> 
> This behaviour was introducted by a recent release and fixed with the most latest release, presumably because of the linked PR.

Yes it would effect both ldap and oidc logins equally.

**Comment by caspereijkens** [comment]
We are still encountering this issue when logging in to MinIO Console in RELEASE.2022-08-26T19-53-15Z. 
Regularly we see the following message upon clicking the `Login with SSO` button.
```
Error from IDP
An error occurred, please try again
Role arn:minio:iam:::role/dummy-internal does not exist
```
Also the problem that @codemicro mentioned is still there
> It's also worth noting that this bug also appeared to have stopped OIDC from being displayed as a SSO option on the login screen at all, in favour of the standard username/password form. This was despite OIDC being properly configured.
> 
> This behaviour was introducted by a recent release and fixed with the most latest release, presumably because of the linked PR.

**Comment by harshavardhana** [comment]
@donatello can you check this ?

**Comment by donatello** [comment]
> We are still encountering this issue when logging in to MinIO Console in RELEASE.2022-08-26T19-53-15Z. Regularly we see the following message upon clicking the `Login with SSO` button.
> 
> ```
> Error from IDP
> An error occurred, please try again
> Role arn:minio:iam:::role/dummy-internal does not exist
> ```
> 
> Also the problem that @codemicro mentioned is still there
> 
> > It's also worth noting that this bug also appeared to have stopped OIDC from being displayed as a SSO option on the login screen at all, in favour of the standard username/password form. This was despite OIDC being properly configured.
> > This behaviour was introducted by a recent release and fixed with the most latest release, presumably because of the linked PR.

@caspereijkens Could you share what your minio configuration for openid providers looks like? I am not able to reproduce this issue in the last release (or master branch), with a local dex server:

```shell
export MINIO_IDENTITY_OPENID_CONFIG_URL="http://localhost:5556/dex/.well-known/openid-configuration"
export MINIO_IDENTITY_OPENID_CLIENT_ID="minio-client-app"
export MINIO_IDENTITY_OPENID_CLIENT_SECRET="minio-client-app-secret"
export MINIO_IDENTITY_OPENID_ROLE_POLICY="consoleAdmin"
export MINIO_IDENTITY_OPENID_SCOPES="openid,groups"
export MINIO_IDENTITY_OPENID_REDIRECT_URI="http://127.0.0.1:10000/oauth_callback"

```

**Comment by caspereijkens** [comment]
@donatello Thanks for testing that. We are currently working with:

```
env: 
- name: MINIO_IDENTITY_OPENID_CONFIG_URL 
  value: https://xxx/adfs/.well-known/openid-configuration       
- name: MINIO_IDENTITY_OPENID_CLAIM_NAME 
  value: appid
- name: MINIO_IDENTITY_OPENID_CLAIM_PREFIX
- name: MINIO_IDENTITY_OPENID_SCOPES     
  value: openid,allatclaims     
- name: MINIO_IDENTITY_OPENID_REDIRECT_URI        
  value: https://ui.xxx/oauth_callback       
- name: MINIO_BROWSER_REDIRECT_URL       
  value: https://ui.xxx    
- name: MINIO_SERVER_URL        
  value: https://xxx
- name: MINIO_IDENTITY_OPENID_COMMENT  
- name: MINIO_IDENTITY_TLS_ENABLE        
  value: "true"        
- name: MINIO_IDENTITY_TLS_SKIP_VERIFY   
  value: "false" 
```

Edit: 
To reproduce this issue, we log in and out a few times in a row.

**Comment by donatello** [comment]
I'm still unable to reproduce the issue.

Some things to check:

1. If running distributed minio, check that all nodes are running the latest version
2. There is perhaps a stale cache in the browser? Try a new browser instance or clear caches.

Please share the exact error messages (e.g. screenshot) you get.

**Comment by caspereijkens** [comment]
Hi donatello,

Thanks, I have checked your suggestions but unfortunately they did not help. 

Usually we are able to login, but regularly it fails.

We get a mixture of the following screens after clicking the `Login with SSO` button:
![image (2)](https://user-images.githubusercontent.com/64551820/188900118-eb17793a-eb33-4eba-9d33-9b9e90737520.png)
![image (1)](https://user-images.githubusercontent.com/64551820/188900124-6ba88b31-53da-485b-bf21-58de25c9eb1c.png)
![image](https://user-images.githubusercontent.com/64551820/188900127-f4065f29-42ad-4035-81da-308953a63f44.png)

**Comment by donatello** [comment]
Thanks, we are able to reproduce this issue - it is because after the redirect from the openid server, the request lands on a different server due to a load balancer. We are looking into finding and fixing the root cause.

**Comment by caspereijkens** [comment]
That makes sense, thanks a lot!

**Comment by harshavardhana** [comment]
@caspereijkens as a workaround you can let your console ingress to use `ip_hash` based sticky sessions.

**Comment by Timost** [comment]
For reference, this might also fix https://github.com/minio/console/issues/2214
