### ISSUE TITLE
Tier info cannot be displayed correctly

### ISSUE THREAD

**Issue by sario-code** [minio/minio#18070]
Tier info cannot be displayed correctly.But the event log and destination bucket can see that the file has been transferred.
![image](https://github.com/minio/minio/assets/16344059/16eae9dc-c8d6-4465-aad2-07a42de94523)
![image](https://github.com/minio/minio/assets/16344059/0f0d7bc5-0ce3-433b-86b3-d0612a090f41)

![image](https://github.com/minio/minio/assets/16344059/0febbb48-963d-478d-9bbe-9774d519a932)
![image](https://github.com/minio/minio/assets/16344059/dc21d1a5-c502-4c47-a3ce-41173895ae0a)

## Expected Behavior
Tier info can be displayed correctly

## Current Behavior
Tier info cannot be displayed correctly

## Steps to Reproduce (for bugs)
1.Add tier settings
2.Set bucket lifecycle
3.Wait until the life cycle comes

## Your Environment

* Version used (`minio --version`):
minio version RELEASE.2023-09-07T02-05-02Z (commit-id=703ed46d79bba51d5d781e2297ca0216c99c8536)
Runtime: go1.21.1 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
* Server setup and configuration:
Docker version 24.0.2, build cb74dfc
* Operating System and version (`uname -a`):
Linux 4.15.0-213-generic #224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Tier info is not instantaneous, it builds itself based on the scanner routine which runs in cycles.

**Comment by sario-code** [comment]
> 层信息不是即时的，它是基于循环运行的扫描程序例程自行构建的。



> Tier info is not instantaneous, it builds itself based on the scanner routine which runs in cycles.

The life cycle I set is one day, but now it has been tree days

**Comment by harshavardhana** [comment]
> > 层信息不是即时的，它是基于循环运行的扫描程序例程自行构建的。
> 
> > Tier info is not instantaneous, it builds itself based on the scanner routine which runs in cycles.
> 
> The life cycle I set is one day, but now it has been tree days

Lifecycle even if set for a day the actual transition happens in 3 days.

The scanner would update this in a bit.

**Comment by sario-code** [comment]
> > > 层信息不是即时的，它是基于循环运行的扫描程序例程自行构建的。
> > 
> > 
> > > Tier info is not instantaneous, it builds itself based on the scanner routine which runs in cycles.
> > 
> > 
> > The life cycle I set is one day, but now it has been tree days
> 
> Lifecycle even if set for a day the actual transition happens in 3 days.
> 
> The scanner would update this in a bit.

Okay, I'll observe it for a while . How long can the minimum life cycle be set to?

**Comment by harshavardhana** [comment]
> > > > 层信息不是即时的，它是基于循环运行的扫描程序例程自行构建的。
> > > 
> > > 
> > > > Tier info is not instantaneous, it builds itself based on the scanner routine which runs in cycles.
> > > 
> > > 
> > > The life cycle I set is one day, but now it has been tree days
> > 
> > 
> > Lifecycle even if set for a day the actual transition happens in 3 days.
> > The scanner would update this in a bit.
> 
> Okay, I'll observe it for a while . How long can the minimum life cycle be set to?

1 day but it doesn't run in 24hrs it runs after the object has expired for a day.

**Comment by aaa930811** [comment]
> Okay

Okay,thank you very much

**Comment by sario-code** [comment]
> > > > > 层信息不是即时的，它是基于循环运行的扫描程序例程自行构建的。
> > > > 
> > > > 
> > > > > Tier info is not instantaneous, it builds itself based on the scanner routine which runs in cycles.
> > > > 
> > > > 
> > > > The life cycle I set is one day, but now it has been tree days
> > > 
> > > 
> > > Lifecycle even if set for a day the actual transition happens in 3 days.
> > > The scanner would update this in a bit.
> > 
> > 
> > Okay, I'll observe it for a while . How long can the minimum life cycle be set to?
> 
> 1 day but it doesn't run in 24hrs it runs after the object has expired for a day.

Okay,thank you very much

**Comment by harshavardhana** [comment]
@aaa930811 can you explain how you setup the tiering? for some reason, it looks like you tiered to yourself.

**Comment by sario-code** [comment]
> @aaa930811 can you explain how you setup the tiering? for some reason, it looks like you tiered to yourself.

![image](https://github.com/minio/minio/assets/16344059/df060849-d5e0-4670-9fd8-932be31e738f)
just like this

**Comment by sario-code** [comment]
> @aaa930811 can you explain how you setup the tiering? for some reason, it looks like you tiered to yourself.

I have deployed 2 clusters on one machine, one of which uses NVME  storage as hot storage, the another uses SAS hard drive for long-term storage. Just for faster upload speed

**Comment by harshavardhana** [comment]
@aaa930811 we will get back.

**Comment by rensongqi** [comment]
@harshavardhana 
Hi, I have configured Lifecycle for the bucket using `minio-go/v7`, set the data to transition to the target tier after 1 day, and currently after 7 days the data has not transitioned to the target tier.   How do I check the current minio transition logs?
![image](https://github.com/minio/minio/assets/49969527/8caffa7f-886b-4d55-8ce8-5d71db610ca1)

Current minio metrics Info:
- Objects: 193M
- Reported Usage: 76TiB

`upload` bucket metrics Info:
- Objects: 5693
- Usage: 2.1TiB

Current minio version: 
```bash
minio version RELEASE.2022-08-25T07-17-05Z (commit-id=18dffb26e7aba09074704d169517285ac3870e86)
Runtime: go1.18.5 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2022 MinIO, Inc.
```
Target minio tier version:
```bash
minio version RELEASE.2023-09-23T03-47-50Z (commit-id=22041bbcc469f5ac84207d09b4c4db326ec5fd57)
Runtime: go1.21.1 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```

**Comment by klauspost** [comment]
@rensongqi Please don't hijack issues with unrelated stuff. Use the latest version - we only accept issues on latest version. Open an issue if still a problem. Show how you determined that tiering isn't happening.

PS. Tiering will not remove objects locally, it will keep the metadata and move the *data* to second tier. This is mostly transparent.
