### ISSUE TITLE
[distributed] `exec-concurrent TestRemovePartiallyUploaded` fails when just one of the node is permanently down.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#3301]
- When one of the node is permanently down `exec-concurrent TestRemovePartiallyUploaded` fails.
## Expected Behavior

- Test to pass since just one of the node is down and quorum is satisfied.
## Current Behavior

- Fails with `Specified Multipart Doesn't exist error`.
## Possible Solution

- Not sure.
## Steps to Reproduce (for bugs)

1. Bring any one of the node down.

2.Run `exec-concurrent TestRemovePartiallyUploaded`.  [Click here](https://github.com/minio/perftest/tree/master/exec-concurrent) for more info on exec-concurrent tests.

## Context

- Test with just one node permanently down.
## Your Environment

* Version used: 0b9f0d14a193961c87e2950dd439648de36fb651

**Comment by krisis** [comment]
@hackintoshrao could you re-run this test now that #3274 is fixed?

**Comment by hackintoshrao** [comment]
Yes. The issue still exists.

**Comment by harshavardhana** [comment]
> Yes. The issue still exists.

Will validate @hackintoshrao

**Comment by harshavardhana** [comment]
what was the final status here? @hackintoshrao @krisis .

**Comment by hackintoshrao** [comment]
The issue persists. Now that https://github.com/minio/minio/issues/3274 is opened that has to be fixed first.

**Comment by harshavardhana** [comment]
> The issue persists. Now that #3274 is opened that has to be fixed first.

This error occurs due to the same reason of all the multipart issues when an on-going multipart id is not present on one of the nodes.. We have to bring in healing. 

Also update minio-go @vadmeste introduced a mechanism where the upload-ID will be re-negotiated.

**Comment by hackintoshrao** [comment]
Will revalidate nce the patches are in.

**Comment by harshavardhana** [comment]
ping @hackintoshrao - were you able to validate this again?

**Comment by harshavardhana** [comment]
Taking this.

**Comment by harshavardhana** [comment]
Closing this @hackintoshrao - re-open if seen again.
