### ISSUE TITLE
brew services minio typo

### ISSUE THREAD

**Issue by naxmefy** [minio/minio#3564]
## Expected Behavior
```Shell
$ brew services start minio
```
should execute minio server with defined arguments inside ``` homebrew.mxcl.minio.plist ```

## Current Behavior
it doesn't start the minio process

## Possible Solution
inside ``` minio.rb ``` the line 58

currently:
```
<string>--address :9000</string>
```

should be
```
<string>--address=:9000</string>
```

## Steps to Reproduce (for bugs)
1. ``` brew install minio ```
2. ``` brew services start minio ```
3. console is printing
```
Jan 11 15:04:41 My-MacBook-Pro com.apple.xpc.launchd[1] (homebrew.mxcl.minio[39214]): Service exited with abnormal code: 1
Jan 11 15:04:41 My-MacBook-Pro com.apple.xpc.launchd[1] (homebrew.mxcl.minio): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
```
4. log is:
```
Unknown flags. ‘--config-dir=etc/minio, --address :9000, var/minio’
```

## Context
i could not run minio via brew service

## Your Environment
* Version used:
```
Version: 2016-12-13T17:19:42Z
Release-Tag: RELEASE.2016-12-13T17-19-42Z
Commit-ID: 29d72b84c07f9555f83a6485fe8291e18d23811b
```
* Environment name and version (e.g. nginx 1.9.1): Shell? Brew? wtf?
* Server type and version: server?
* Operating System and version: OS X El Capitan 10.11.6
* Link to your project: no project existing yet

## Example homebrew.mxcl.minio.plist (base ond mongodb.plist)
```XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>homebrew.mxcl.minio</string>
  <key>ProgramArguments</key>
  <array>
    <string>/usr/local/opt/minio/bin/minio</string>
    <string>server</string>
    <string>--config-dir=/usr/local/etc/minio</string>
    <string>--address=:9000</string>
    <string>/usr/local/var/minio</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>WorkingDirectory</key>
  <string>/usr/local</string>
  <key>StandardErrorPath</key>
  <string>/usr/local/var/log/minio/output.log</string>
  <key>StandardOutPath</key>
  <string>/usr/local/var/log/minio/output.log</string>
</dict>
</plist>
```

## Example minio.rb for homebrew
```Ruby
class Minio < Formula
  desc "Amazon S3 compatible object storage server"
  homepage "https://github.com/minio/minio"
  url "https://github.com/minio/minio.git",
    :tag => "RELEASE.2016-12-13T17-19-42Z",
    :revision => "29d72b84c07f9555f83a6485fe8291e18d23811b"
  version "20161213171942"

  depends_on "go" => :build

  def install
    ENV["GOPATH"] = buildpath

    clipath = buildpath/"src/github.com/minio/minio"
    clipath.install Dir["*"]

    cd clipath do
      if build.head?
        system "go", "build", "-o", buildpath/"minio"
      else
        release = `git tag --points-at HEAD`.chomp
        version = release.gsub(/RELEASE\./, "").chomp.gsub(/T(\d+)\-(\d+)\-(\d+)Z/, 'T\1:\2:\3Z')
        commit = `git rev-parse HEAD`.chomp
        proj = "github.com/minio/minio"

        system "go", "build", "-o", buildpath/"minio", "-ldflags", <<-EOS.undent
            -X #{proj}/cmd.Version=#{version}
            -X #{proj}/cmd.ReleaseTag=#{release}
            -X #{proj}/cmd.CommitID=#{commit}
            EOS
      end
    end

    bin.install buildpath/"minio"

    (etc+"minio").mkpath
    (var+"minio").mkpath
    (var+"log/minio").mkpath
  end

  plist_options :manual => "minio server"

  def plist; <<-EOS.undent
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
   <plist version="1.0">
    <dict>
      <key>Label</key>
      <string>#{plist_name}</string>
      <key>ProgramArguments</key>
      <array>
        <string>#{opt_bin}/minio</string>
        <string>server</string>
        <string>--config-dir=#{etc}/minio</string>
        <string>--address=:9000</string>
        <string>#{var}/minio</string>
      </array>
      <key>RunAtLoad</key>
      <true/>
      <key>KeepAlive</key>
      <true/>
      <key>WorkingDirectory</key>
      <string>#{HOMEBREW_PREFIX}</string>
      <key>StandardErrorPath</key>
      <string>#{var}/log/minio/output.log</string>
      <key>StandardOutPath</key>
      <string>#{var}/log/minio/output.log</string>
    </dict>
    </plist>
    EOS
  end

  test do
    system "#{bin}/minio", "version"
  end
end
```

**Comment by harshavardhana** [comment]
Thanks @naxmefy - we will fix it.

**Comment by harshavardhana** [comment]
Sent a PR upstream @naxmefy  - https://github.com/Homebrew/homebrew-core/pull/8743

**Comment by naxmefy** [comment]
i am not really familiar with homebrew formulars - that's the reason why i posted the solution here

**Comment by harshavardhana** [comment]
> i am not really familiar with homebrew formulars - that's the reason why i posted the solution here

No problem @naxmefy - it should have been done like this in first place. Thanks for that.

**Comment by harshavardhana** [comment]
Fixed upstream.

**Comment by joelanford** [comment]
Sorry to revive an old issue, but this seems to still be a problem in the latest version of the brew formula. I'm getting the following error message in the output.log file:
```
Incorrect Usage: flag provided but not defined: -address :9000
```

This line is still present in the plist file:
```
<string>--address :9000</string>
```

Adding an equal sign fixes the problem:
```
<string>--address=:9000</string>
```

**Comment by harshavardhana** [comment]
@joelanford are you using `brew install minio` or `brew install minio/stable/minio` ? we recommend the latter.

**Comment by joelanford** [comment]
I was using `brew install minio`, but I uninstalled it and tried `brew install minio/stable/minio` as well. It seems to have the same problem.

I'm guessing these are the relevant files/lines?
* `minio`: https://github.com/Homebrew/homebrew-core/blob/master/Formula/minio.rb#L66
* `minio/stable/minio`: https://github.com/minio/homebrew-stable/blob/master/minio.rb#L44

Slightly off topic, but I also noticed that there may be permissions issues with the `#{var}/log/minio` directory.  Does it need to be added to the post_install function?
```ruby
  def post_install
    (var/"minio").mkpath
    (var/"log/minio").mkpath
    (etc/"minio").mkpath
  end
```

**Comment by harshavardhana** [comment]
> I was using brew install minio, but I uninstalled it and tried brew install minio/stable/minio as well. It seems to have the same problem.
> 
> I'm guessing these are the relevant files/lines?
> 
> minio: https://github.com/Homebrew/homebrew-core/blob/master/Formula/minio.rb#L66
> minio/stable/minio: https://github.com/minio/homebrew-stable/blob/master/minio.rb#L44
> Slightly off topic, but I also noticed that there may be permissions issues with the #{var}/log/minio directory. Does it need to be added to the post_install function?
> 
>   def post_install
>     (var/"minio").mkpath
>     (var/"log/minio").mkpath
>     (etc/"minio").mkpath
>   end

That is a good suggestion, we are not native MacOS users so feel free to send a PR if you can :-)

**Comment by harshavardhana** [comment]
Fixed by https://github.com/minio/homebrew-stable/pull/8 - Thanks a lot for the fix @joelanford
