### ISSUE TITLE
Server requires content-length header in chunked encoding (streaming) requests

### ISSUE THREAD

**Issue by donatello** [minio/minio#4152]
The Ruby library fog when uploading files to Minio/S3, uses chunked encoding, but does not send the "content-length" header - however Minio server requires it. Presumably fog has the same behaviour wrt S3 and so we need to see if content-length header is actually required in Minio server's chunked request implementation.

More context of how the issue was found is here - https://github.com/minio/minio-boshrelease/issues/5

## Expected Behavior

fog library should "just work" with Minio server.

## Current Behavior

Minio server returns error saying that "content-length" header is required.

## Possible Solution

Currently unknown.

## Steps to Reproduce (for bugs)

See linked issue above.

## Context

Related to supporting Minio as a blobstore for BOSH.

## Your Environment

* Version used:
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by deekoder** [comment]
does this block #4089? and is there a workaround?

**Comment by donatello** [comment]
Since the last release, this issue was fixed in b62cd8ed84eb29cab0b667e07e671f33c1465760

fog library works fine on master. Tested with https://gist.github.com/donatello/e8f442f92e388bc62f79c6e40d49caf3

**Comment by harshavardhana** [comment]
> Since the last release, this issue was fixed in b62cd8e
> 
> fog library works fine on master. Tested with https://gist.github.com/donatello/e8f442f92e388bc62f79c6e40d49caf3

So this means we can document how to use `bosh` to store blobs on Minio now?

**Comment by donatello** [comment]
No that is not yet the case. The original person who tried, was using Minio as a blobstore for Cloud Foundry - this appears to be different from using it as a blobstore in BOSH.

**Comment by mcastilho** [comment]
I am still getting errors with latest version of Minio that returns 411 Length Required using Fog

```
--- Caused by: ---
     # Excon::Error::LengthRequired:
     #   Expected(200) <=> Actual(411 Length Required)
     #   excon.error.response
     #     :body          => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>MissingContentLength</Code><Message>You must provide the Content-Length HTTP header.</Message><Key></Key><BucketName></BucketName><Resource>/test-uploads/ACCOUNT_LOGOS/1/inverted_logo.png</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>"
     #     :cookies       => [
     #     ]
     #     :headers       => {
     #       "Accept-Ranges"    => "bytes"
     #       "Content-Type"     => "application/xml"
     #       "Date"             => "Thu, 27 Apr 2017 15:41:32 GMT"
     #       "Server"           => "Minio/RELEASE.2017-04-25T01-27-49Z (darwin; amd64)"
     #       "Vary"             => "Origin"
     #       "X-Amz-Request-Id" => "14B94B6F49A7A146"
     #     }
     #     :host          => "localhost"
     #     :local_address => "::1"
     #     :local_port    => 51391
     #     :path          => "/test-uploads/ACCOUNT_LOGOS/1/inverted_logo.png"
     #     :port          => 9000
     #     :reason_phrase => "Length Required"
     #     :remote_ip     => "127.0.0.1"
     #     :status        => 411
     #     :status_line   => "HTTP/1.1 411 Length Required\r\n"
```

**Comment by harshavardhana** [comment]
The fix is not released yet.
