### ISSUE TITLE
Failed to lookup minio1 on Docker Swarm

### ISSUE THREAD

**Issue by rolandrajko** [minio/minio#4761]
Hi,

I would like to deploy a Minio stack on Docker Swarm, but I have got only the following message every time: `Failed to resolve hosts... Failed to lookup minio1`

## Expected Behavior
I followed your instructions in [docs/Deploy Minio on Docker Swarm](https://docs.minio.io/docs/deploy-minio-on-docker-swarm), and read the article [The complete guide to attach a Docker volume with Minio on your Docker Swarm Cluster](http://firepress.org/blog/the-complete-guide-to-attach-a-docker-volume-with-minio-on-your-docker-swarm-cluster/), so I expected it will start up quickly and successfully.

## Current Behavior
In the logs I get continously the following message: 
```
minio1.1.xik0ml96hy6l@manager1    | .Failed to lookup minio1
minio1.1.xik0ml96hy6l@manager1    | Failed to resolve hosts.. retrying after 1 second.
```
If I try to ping itself (or another element of the Minio stack) with the command `docker exec -it [container_id] ping minio1`, I get the response `ping: bad address 'minio1'`, but if I ping another service on the same overlay network, it's okay.

## Steps to Reproduce (for bugs)
For now I kept only a few lines below in my `docker-minio.yml` file:
```
version: "3.2"

services:
  minio1:
    image: minio/minio:RELEASE.2017-07-24T18-27-35Z
    volumes:
      - /mnt/minio/minio1:/export
    ports:
      - "9001:9000"
    networks:
      - ntw_minio
    deploy:
      placement:
        constraints: [node.hostname == manager1]
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio1/export
    secrets:
      - access_key
      - secret_key

networks:
  ntw_minio:
    external: true

secrets:
  secret_key:
    external: true
  access_key:
    external: true
```
(I tried with named volumes as you described too.)

Steps:
1. `rm -rf /mnt/minio/minio1`
2. `mkdir -p /mnt/minio/minio1`
3. `echo "minio_access_key" | docker secret create access_key -`
4. `echo "minio_secret_key" | docker secret create secret_key -`
5. `docker stack deploy -c docker-minio.yml minio_stack`

I also tried with the following command:
 ```
docker service create \
    --name minio1 \
    --network ntw_minio \
    --replicas "1" \
    -p "9001:9000" \
    --constraint 'node.hostname==manager1' \
    --secret access_key \
    --secret secret_key \
    --mount type=bind,src=/mnt/minio/minio1,dst=/export \
    minio/minio:RELEASE.2017-07-24T18-27-35Z \
    server http://minio1/export
```

## My Environment
* Version used (`minio version`):
```
Version: 2017-07-24T18:27:35Z
Release-Tag: RELEASE.2017-07-24T18-27-35Z
Commit-ID: 461d60095df56cdb1370f20135429a5a24b400b3
```
* Docker version:
```
Docker version 17.05.0-ce, build 89658be
```
* Operating System and version (`uname -a`): 
```
Linux manager1 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
* Server type: **AWS EC2 t2.small @ eu-west-1**

Every other services (e.g. NGINX) work like a charm, so I guess I configured the Swarm, the AWS Security Groups etc. correctly.

I tried everything which came to my mind.

Please help me! Thanks.

**Comment by nitisht** [comment]
@rolandrajko can you please attach the complete `docker-minio.yml` you are using. It may help identifying the issue

**Comment by rolandrajko** [comment]
```
version: "3.2"

services:
  minio1:
    image: minio/minio:RELEASE.2017-07-24T18-27-35Z
    volumes:
      - minio1-data:/export
    ports:
      - "9001:9000"
    networks:
      - ntw_minio
    deploy:
      placement:
        constraints: [node.hostname == manager1]
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    secrets:
      - access_key
      - secret_key

  minio2:
    image: minio/minio:RELEASE.2017-07-24T18-27-35Z
    volumes:
      - minio2-data:/export
    ports:
      - "9002:9000"
    networks:
      - ntw_minio
    deploy:
      placement:
        constraints: [node.hostname == worker1]
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    secrets:
      - access_key
      - secret_key

  minio3:
    image: minio/minio:RELEASE.2017-07-24T18-27-35Z
    volumes:
      - minio3-data:/export
    ports:
      - "9003:9000"
    networks:
      - ntw_minio
    deploy:
      placement:
        constraints: [node.hostname == worker2]
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    secrets:
      - access_key
      - secret_key

  minio4:
    image: minio/minio:RELEASE.2017-07-24T18-27-35Z
    volumes:
      - minio4-data:/export
    ports:
      - "9004:9000"
    networks:
      - ntw_minio
    deploy:
      placement:
        constraints: [node.hostname == worker3]
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    secrets:
      - access_key
      - secret_key

volumes:
  minio1-data: {}
  minio2-data: {}
  minio3-data: {}
  minio4-data: {}

networks:
  ntw_minio:
    external: true

secrets:
  secret_key:
    external: true
  access_key:
    external: true
```
The `ntw_minio` network itself was created by:
```
docker network create -d overlay --attachable nwt_minio
```

**Comment by nitisht** [comment]
Thanks! Let me get back to you on this

**Comment by nitisht** [comment]
@rolandrajko can you pls change network to 

```
networks:
  ntw_minio:
    driver: overlay
```
and then run `docker stack deploy -c docker-minio.yml minio_stack` without creating the network yourself.

**Comment by rolandrajko** [comment]
I got the same result:
```
minio_stack_minio1.1.c17j1dw5u974@manager1    | Failed to resolve hosts.. retrying after 1 second.
minio_stack_minio1.1.c17j1dw5u974@manager1    | .Failed to lookup minio1
minio_stack_minio1.1.c17j1dw5u974@manager1    | .Failed to lookup minio2
minio_stack_minio1.1.c17j1dw5u974@manager1    | .Failed to lookup minio3
minio_stack_minio1.1.c17j1dw5u974@manager1    | .Failed to lookup minio4
```
By `docker service ps --no-trunc minio_stack_minio1` the exact error is:
```
task: non-zero exit (137): dockerexec: unhealthy container
```

**Comment by nitisht** [comment]
The error `dockerexec: unhealthy container` makes me think this is related to this issue https://github.com/moby/moby/issues/26498

Essentially, Swarm thinks container is unhealthy and kills it before the application starts properly. Can you please try https://github.com/moby/moby/pull/28938#issuecomment-301736698

I mean use the `docker service create` command you used earlier and then add the `--health-start-period=120s` flag.

**Comment by rolandrajko** [comment]
1. Updated the Docker: `Docker version 17.06.0-ce, build 02c1d87`
2. Created an overlay network: `docker network create -d overlay --attachable ntw_minio`
3. Created the service:
```
docker service create \
    --name minio1 \
    --network ntw_minio \
    --replicas "1" \
    -p "9001:9000" \
    --constraint 'node.role==manager' \
    --mount type=bind,src=/mnt/minio/minio1,dst=/export \
    -e "MINIO_ACCESS_KEY=access_key" \
    -e "MINIO_SECRET_KEY=secret_key" \
    --health-start-period=120s \
    --restart-delay=10s \
    --restart-window=120s \
    minio/minio \
    server http://minio1/export
```
4. Got the well known messages:
```
minio1.1.m1lqm89msph0@manager1    | Waiting for all hosts to resolve....Failed to lookup minio1
minio1.1.m1lqm89msph0@manager1    | Failed to resolve hosts.. retrying after 1 second.
minio1.1.m1lqm89msph0@manager1    | .Failed to lookup minio1
```
Otherwise if I run the following command, everything is fine:
```
docker service create \
    --name minio1 \
    --network ntw_minio \
    --replicas "1" \
    -p "9001:9000" \
    --constraint 'node.role==manager' \
    --mount type=bind,src=/mnt/minio/minio1,dst=/export \
    -e "MINIO_ACCESS_KEY=access_key" \
    -e "MINIO_SECRET_KEY=secret_key" \
    --health-start-period=120s \
    --restart-delay=10s \
    --restart-window=120s \
    minio/minio \
    server /export
```
Can I try to set anything else?

**Comment by nitisht** [comment]
@rolandrajko is it possible to access your setup?

**Comment by rolandrajko** [comment]
Sorry, I guess I can't grant access to you, but I try to provide all the information you need.

**Comment by nitisht** [comment]
> Sorry, I guess I can't grant access to you, but I try to provide all the information you need.

I see. We have tested Minio on Swarm and it works well, but let me try to reproduce this locally with your `.yaml` files and get back to you.

**Comment by nitisht** [comment]
@rolandrajko I tried to reproduce the issue and looks like there was a problem with healthcheck in Docker Swarm mode. 

Swarm routes traffic only to containers that report `healthy` status, while Minio in distributed mode needs to talk to other peers before it can respond to healthcheck probe. As the Minio containers were not able to talk to each other, you were getting 

```
minio_stack_minio1.1.c17j1dw5u974@manager1    | Failed to resolve hosts.. retrying after 1 second.
minio_stack_minio1.1.c17j1dw5u974@manager1    | .Failed to lookup minio1
minio_stack_minio1.1.c17j1dw5u974@manager1    | .Failed to lookup minio2
minio_stack_minio1.1.c17j1dw5u974@manager1    | .Failed to lookup minio3
minio_stack_minio1.1.c17j1dw5u974@manager1    | .Failed to lookup minio4
```

However, it is fixed. Can you please try this image `nitisht/minio:swarm4` in your Swarm setup. After you validate, we'll fix it in the master.

**Comment by rolandrajko** [comment]
It looks good.
```
Status:         4 Online, 0 Offline.
```
Thank you.

**Comment by RiwanBodereau** [comment]
Hello,

I would like to re-open the issue.

I had the same problem as the OP. And yes from now on it works fine with @nitisht fork (nitisht/minio:swarm4).

As i can see it has been merged to the master last year, but when using the minio latest version i still have the same issue as mentionned..

Therefore im unable to use latest minio version, and stuck with this old version.
Im using docker-swarm and traefik.

docker version : `Docker version 17.12.0-ce, build c97c6d6`
Here is my yaml :

```
version: '3.2'

services:
  test_minio1:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=iMooMevu5ku3Eech
      - MINIO_SECRET_KEY=eayei1muu3ethooch7ooZohbaNgouPho
      - MINIO_BROWSER=off
    volumes:
      - /export1/test:/export1
      - /export2/test:/export2
    networks:
      - proxy_traefik-net
    deploy:
      labels:
        - "traefik.backend=test"
        - "traefik.frontend.rule=Host:test.s3.net"
        - "traefik.port=9000"
        - "traefik.docker.network=proxy_traefik-net"
      placement:
        constraints: [node.hostname == MINIO-NODE01]
    command: server http://test_minio1/export1 http://test_minio1/export2 http://test_minio2/export1 http://test_minio2/export2

  test_minio2:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=iMooMevu5ku3Eech
      - MINIO_SECRET_KEY=eayei1muu3ethooch7ooZohbaNgouPho
      - MINIO_BROWSER=off
    volumes:
      - /export1/test:/export1
      - /export2/test:/export2
    networks:
      - proxy_traefik-net
    deploy:
      labels:
        - "traefik.backend=test"
        - "traefik.frontend.rule=Host:test.s3.net"
        - "traefik.port=9000"
        - "traefik.docker.network=proxy_traefik-net"
      placement:
        constraints: [node.hostname == MINIO-NODE02]
    command: server http://test_minio1/export1 http://test_minio1/export2 http://test_minio2/export1 http://test_minio2/export2

networks:
  proxy_traefik-net:
    external: true
```

traefik yaml
```
version: '3.2'

services:
  traefik:
    image: traefik
    networks:
      - traefik-net
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/traefik/:/etc/traefik/
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 45s
        monitor: 15s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 60s

networks:
  traefik-net:
    driver: overlay
```

traefik toml :
```
logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

[entryPoints]
 [entryPoints.http]
 address = ":80"
 compress = false
   [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/wildcard.s3.net.crt"
      keyFile = "/etc/traefik/certs/wildcard.s3.net.key"

[web]
address = ":8080"
  [web.statistics]
    recentErrors = 10

[docker]
watch = true
swarmmode = true
```

docker logs : 
```
Time: 11:16:54 UTC 04/24/2018
Error: lookup test_minio2 on 127.0.0.11:53: no such host
       elapsedTime=1 second elapsed, host=test_minio2
       1: cmd/net.go:106:cmd.getHostIP4()
       2: cmd/net.go:294:cmd.isLocalHost()
       3: cmd/endpoint.go:146:cmd.NewEndpoint()
       4: cmd/endpoint.go:192:cmd.NewEndpointList()
       5: cmd/endpoint.go:271:cmd.CreateEndpoints()
       6: cmd/endpoint-ellipses.go:245:cmd.createServerEndpoints()
       7: cmd/server-main.go:130:cmd.serverHandleCmdArgs()
       8: cmd/server-main.go:185:cmd.serverMain()

API: SYSTEM()
Time: 11:17:00 UTC 04/24/2018
Error: lookup test_minio2 on 127.0.0.11:53: no such host
       host=test_minio2, elapsedTime=7 seconds elapsed
       1: cmd/net.go:106:cmd.getHostIP4()
       2: cmd/net.go:294:cmd.isLocalHost()
       3: cmd/endpoint.go:146:cmd.NewEndpoint()
       4: cmd/endpoint.go:192:cmd.NewEndpointList()
       5: cmd/endpoint.go:271:cmd.CreateEndpoints()
       6: cmd/endpoint-ellipses.go:245:cmd.createServerEndpoints()
       7: cmd/server-main.go:130:cmd.serverHandleCmdArgs()
       8: cmd/server-main.go:185:cmd.serverMain()
```

Thanks in advance
