### ISSUE TITLE
Automatic healthcheck still doesn't work with latest image on docker hub

### ISSUE THREAD

**Issue by zackw** [minio/minio#5652]
## Expected Behavior

"docker ps" should not report the status of a minio/minio container as "unhealthy".

## Current Behavior

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                      PORTS                      NAMES
bb45b34b1fab        minio/minio         "/usr/bin/docker-e..."   13 minutes ago      Up 12 minutes (unhealthy)   127.0.0.1:9000->9000/tcp   minio_files
```

This appears to be exactly the same problem as #5010.  Inspecting the contents of the image, the fix that was supposedly merged in #5011 is not present in `healthcheck.sh`: 

```
$ grep curl minio_image/usr/bin/healthcheck.sh
        http_response=$(curl -s -k -o /dev/null -I -w "%{http_code}" ${scheme}${address}${resource})
        http_response_body=$(curl -k -s ${scheme}${address}${resource})
            http_response=$(curl -s -k -o /dev/null -I -w "%{http_code}" ${scheme}${address}${resource})
```

Those are supposed to have `-H "User-Agent: Mozilla"` in there.

### `minio version`:

```
Version: 2018-03-12T21:25:28Z
Release-Tag: RELEASE.2018-03-12T21-25-28Z
Commit-ID: 4a4d1d1b82046a2af62381434bcbff1d748db477
```

### Docker image:

```
$ docker image inspect c1eb23ac57fb
[
    {
        "Id": "sha256:c1eb23ac57fb6f22dba44f715211be756c41ca548eac415df5bee1356543de21",
        "RepoTags": [
            "minio/minio:latest"
        ],
        "RepoDigests": [
            "minio/minio@sha256:0b76f67bc72d2e6fb8a2fa1c802e2ea0b7839b6079dfbdc549a528adaff9b7b3"
        ],
        ...
    }
]
```

This is the `minio/minio` image from Docker Hub as of today (2018-03-14).

**Comment by harshavardhana** [comment]
We fixed it in #5647 @zackw - we will be making a new release.

**Comment by zackw** [comment]
Please do not close this bug until it has been verified to be fixed with the image you get by doing "docker pull minio/minio".

**Comment by harshavardhana** [comment]
> Please do not close this bug until it has been verified to be fixed with the image you get by doing "docker pull minio/minio".

you can test with `docker pull minio/minio:edge`

**Comment by zackw** [comment]
I believe you that there are code changes in the development branch that address the bug.  However, the recommended-for-production Docker image, `minio/minio`, is still buggy until _it_ is updated.  That's all I was trying to say.  I don't mean to be coming in here out of the blue and telling you how to run your project.  It's just that as a user, it is immensely frustrating to find that the problem you're having corresponds to a _closed_ bug report when you can see that the fix hasn't shipped yet.

**Comment by harshavardhana** [comment]
> I believe you that there are code changes in the development branch that address the bug. However, the recommended-for-production Docker image, minio/minio, is still buggy until it is updated. That's all I was trying to say. I don't mean to be coming in here out of the blue and telling you how to run your project. It's just that as a user, it is immensely frustrating to find that the problem you're having corresponds to a closed bug report when you can see that the fix hasn't shipped yet.

Yes, that is true it was fixed, it is a regression. What I meant in my previous comment was you can test and validate @zackw

**Comment by zackw** [comment]
Yes, I see a working health check with `minio/minio:edge`.

**Comment by harshavardhana** [comment]
> Yes, I see a working health check with minio/minio:edge.

Great, that is all I wanted to know. @zackw  - Thanks for testing.

**Comment by harshavardhana** [comment]
> I believe you that there are code changes in the development branch that address the bug. However, the recommended-for-production Docker image, minio/minio, is still buggy until it is updated. That's all I was trying to say. I don't mean to be coming in here out of the blue and telling you how to run your project. It's just that as a user, it is immensely frustrating to find that the problem you're having corresponds to a closed bug report when you can see that the fix hasn't shipped yet.

A new release has been made which fixes the issue, feel free to re-open if seen again.
