### ISSUE TITLE
requests to distributed minio will wait 60s while a server is lost

### ISSUE THREAD

**Issue by luanshaotong** [minio/minio#8177]
I deployed distributed minio servers on three nodes of kubernetes. I expect that minio will automatically recover data and continue to provide services while a node is lost. When I lost a node, the minio server still provided service, but every time an object was requested, the minio waited 60s time to return the result sometimes (whether or not the object is requested for the first time). 
What is the reason? 
Can I config this value to reduce the wait time? Or after losing the node, do I have to restart a minio instance and heal the data to resume normal request?

## Expected Behavior

I expect to be able to use the distributed minio server normally while a node is lost.

## Current Behavior

Requests using mc or s3cmd sometimes wait 60s before returning while a node is lost.

## Steps to Reproduce (for bugs)

1.deploy distributed minio with 3 instance in kubernetes ( using hostpath )
2.shutdown a kubernetes node with a minio
3.request objects using mc cp or s3cmd get

## Your Environment

* Version used (`minio version`): RELEASE.2017-12-12T01-08-02Z
* Environment name and version (e.g. nginx 1.9.1): kubernetes 1.12

**Comment by harshavardhana** [comment]
> * Version used (`minio version`): RELEASE.2017-12-12T01-08-02Z

are you sure you are running this release?  - This issue has been fixed in all the latest releases @luanshaotong

**Comment by kannappanr** [comment]
@luanshaotong Please try the latest release and let us know if you still see the issue. Closing the issue for now.

**Comment by luanshaotong** [comment]
@harshavardhana @kannappanr 
 I have confounded mc version with minio server version. I'm truely running minio 2018-08-25T01:56:38Z. 
Now I changed image tag to lastest in daemonsets and delete minio pods, but the issue still appears.

**Comment by kannappanr** [comment]
@luanshaotong Can you please provide more information for us to reproduce this issue? Like yml files etc. Do you see any server errors?

**Comment by harshavardhana** [comment]
You should be using the latest 09-05 and let us know

**Comment by luanshaotong** [comment]
@kannappanr @harshavardhana 
This problem is because my application (harbor) loses all data when I upgrade minio to latest 09-05. Now I have reinstalled harbor and the problem is now solved.
Please close this issue.
In addition, can you provide me with a safe hot upgrade plan or data migration solution?

**Comment by harshavardhana** [comment]
> This problem is because my application (harbor) loses all data when I upgrade minio to latest 09-05. Now I have reinstalled harbor and the problem is now solved.

There is no possibility of losing data in that manner just because of upgrades @luanshaotong - can you explain more?

**Comment by luanshaotong** [comment]
After upgrades, I observed no data in the bucket through minio browser. My harbor service is also blocked. Do you mean that minio is recovering data?
@harshavardhana

**Comment by harshavardhana** [comment]
No there is no such thing,  unless you were upgrading in between you were trying to see the objects. There is something else going on, can you reproduce this by downgrading and upgrading again ?

**Comment by harshavardhana** [comment]
What is the backend filesystem under use here? @luanshaotong most probably because of #8240 you may be seeing this issue.

**Comment by kannappanr** [comment]
@luanshaotong Closing this as fixed by #8240 Please feel free to reach out to us if you still see this issue
